#!/usr/bin/env python3
"""
Test suite for Milestone 2: MeshAnalysis Module

Tests the real mesh analysis functionality with generated STL files.
"""

import sys
import os
import struct
import tempfile

# Add the build directory to Python path if not already set
build_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "build", "python")
if os.path.exists(build_dir) and build_dir not in sys.path:
    sys.path.insert(0, build_dir)

try:
    import geom_core_py
except ImportError as e:
    print(f"ERROR: Failed to import geom_core_py: {e}")
    print(f"Make sure to build the project first: ./scripts/build_python.sh")
    print(f"Or set PYTHONPATH to the build directory")
    sys.exit(1)


def write_binary_stl_cube(filepath, size=10.0):
    """
    Generate a binary STL file representing a cube.

    A cube has 6 faces, each made of 2 triangles = 12 triangles total.

    Args:
        filepath: Path to write the STL file
        size: Edge length of the cube (default 10.0)
    """
    half = size / 2.0

    # Define 8 vertices of a cube centered at origin
    vertices = [
        (-half, -half, -half),  # 0: left-bottom-back
        (half, -half, -half),  # 1: right-bottom-back
        (half, half, -half),  # 2: right-top-back
        (-half, half, -half),  # 3: left-top-back
        (-half, -half, half),  # 4: left-bottom-front
        (half, -half, half),  # 5: right-bottom-front
        (half, half, half),  # 6: right-top-front
        (-half, half, half),  # 7: left-top-front
    ]

    # Define 12 triangles (6 faces × 2 triangles each)
    # Each face is defined counter-clockwise when viewed from outside
    triangles = [
        # Back face (-Z)
        (0, 2, 1),
        (0, 3, 2),
        # Front face (+Z)
        (4, 5, 6),
        (4, 6, 7),
        # Left face (-X)
        (0, 4, 7),
        (0, 7, 3),
        # Right face (+X)
        (1, 6, 5),
        (1, 2, 6),
        # Bottom face (-Y)
        (0, 1, 5),
        (0, 5, 4),
        # Top face (+Y)
        (3, 6, 2),
        (3, 7, 6),
    ]

    with open(filepath, "wb") as f:
        # Write 80-byte header (padding to exactly 80 bytes)
        header_text = b"Binary STL generated by geom-core test"
        f.write(header_text + b"\x00" * (80 - len(header_text)))

        # Write triangle count
        f.write(struct.pack("<I", len(triangles)))

        # Write each triangle
        for tri in triangles:
            v0 = vertices[tri[0]]
            v1 = vertices[tri[1]]
            v2 = vertices[tri[2]]

            # Calculate normal (cross product)
            # edge1 = v1 - v0
            edge1 = (v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2])
            # edge2 = v2 - v0
            edge2 = (v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2])

            # normal = edge1 × edge2
            normal = (
                edge1[1] * edge2[2] - edge1[2] * edge2[1],
                edge1[2] * edge2[0] - edge1[0] * edge2[2],
                edge1[0] * edge2[1] - edge1[1] * edge2[0],
            )

            # Write normal (3 floats)
            f.write(struct.pack("<fff", *normal))

            # Write 3 vertices (3 floats each)
            f.write(struct.pack("<fff", *v0))
            f.write(struct.pack("<fff", *v1))
            f.write(struct.pack("<fff", *v2))

            # Write attribute byte count (always 0)
            f.write(struct.pack("<H", 0))


def test_vector3():
    """Test Vector3 class."""
    print("Testing Vector3...")

    v1 = geom_core_py.Vector3(3.0, 4.0, 0.0)
    assert v1.x == 3.0
    assert v1.y == 4.0
    assert v1.z == 0.0

    # Test length
    length = v1.length()
    assert abs(length - 5.0) < 0.001, f"Expected length 5.0, got {length}"

    print(f"  ✓ Vector3 basic operations work")
    print(f"  ✓ Vector3(3, 4, 0).length() = {length}")


def test_load_stl():
    """Test loading an STL file."""
    print("\nTesting STL loading...")

    # Create a temporary STL file
    with tempfile.NamedTemporaryFile(suffix=".stl", delete=False) as f:
        temp_file = f.name

    try:
        # Generate a 10x10x10 cube
        write_binary_stl_cube(temp_file, size=10.0)

        # Load it with Analyzer
        analyzer = geom_core_py.Analyzer()
        success = analyzer.load_stl(temp_file)

        assert success, "Failed to load STL file"

        vertex_count = analyzer.get_vertex_count()
        triangle_count = analyzer.get_triangle_count()

        print(f"  ✓ Loaded STL successfully")
        print(f"  ✓ Vertices: {vertex_count} (expected 8)")
        print(f"  ✓ Triangles: {triangle_count} (expected 12)")

        # A cube has 8 unique vertices after deduplication
        assert vertex_count == 8, f"Expected 8 vertices, got {vertex_count}"

        # A cube has 12 triangles (6 faces × 2 triangles)
        assert triangle_count == 12, f"Expected 12 triangles, got {triangle_count}"

    finally:
        # Clean up temporary file
        if os.path.exists(temp_file):
            os.remove(temp_file)


def test_cube_volume():
    """Test volume calculation on a cube."""
    print("\nTesting volume calculation...")

    # Create a temporary STL file
    with tempfile.NamedTemporaryFile(suffix=".stl", delete=False) as f:
        temp_file = f.name

    try:
        # Generate a 10x10x10 cube (volume = 1000)
        cube_size = 10.0
        expected_volume = cube_size**3

        write_binary_stl_cube(temp_file, size=cube_size)

        analyzer = geom_core_py.Analyzer()
        analyzer.load_stl(temp_file)

        volume = analyzer.get_volume()

        # Allow 1% tolerance for floating point arithmetic
        tolerance = expected_volume * 0.01

        print(f"  ✓ Cube size: {cube_size}×{cube_size}×{cube_size}")
        print(f"  ✓ Calculated volume: {volume:.2f}")
        print(f"  ✓ Expected volume: {expected_volume:.2f}")

        assert (
            abs(volume - expected_volume) < tolerance
        ), f"Volume mismatch: expected {expected_volume}, got {volume}"

    finally:
        if os.path.exists(temp_file):
            os.remove(temp_file)


def test_watertight():
    """Test watertight (manifold) check on a cube."""
    print("\nTesting watertight check...")

    # Create a temporary STL file
    with tempfile.NamedTemporaryFile(suffix=".stl", delete=False) as f:
        temp_file = f.name

    try:
        write_binary_stl_cube(temp_file, size=10.0)

        analyzer = geom_core_py.Analyzer()
        analyzer.load_stl(temp_file)

        is_watertight = analyzer.is_watertight()

        print(f"  ✓ Is watertight: {is_watertight}")

        assert is_watertight, "Cube should be watertight!"

    finally:
        if os.path.exists(temp_file):
            os.remove(temp_file)


def test_bounding_box():
    """Test bounding box calculation."""
    print("\nTesting bounding box...")

    # Create a temporary STL file
    with tempfile.NamedTemporaryFile(suffix=".stl", delete=False) as f:
        temp_file = f.name

    try:
        cube_size = 10.0
        write_binary_stl_cube(temp_file, size=cube_size)

        analyzer = geom_core_py.Analyzer()
        analyzer.load_stl(temp_file)

        bbox = analyzer.get_bounding_box()

        print(f"  ✓ Bounding box: ({bbox.x:.2f}, {bbox.y:.2f}, {bbox.z:.2f})")

        # Each dimension should be approximately cube_size
        tolerance = 0.01
        assert abs(bbox.x - cube_size) < tolerance
        assert abs(bbox.y - cube_size) < tolerance
        assert abs(bbox.z - cube_size) < tolerance

    finally:
        if os.path.exists(temp_file):
            os.remove(temp_file)


def test_legacy_methods():
    """Test that legacy methods still work (backward compatibility)."""
    print("\nTesting legacy methods (backward compatibility)...")

    analyzer = geom_core_py.Analyzer()

    # Test add
    result = analyzer.add(1, 2)
    assert result == 3
    print(f"  ✓ add(1, 2) = {result}")

    # Test load_data
    result = analyzer.load_data("test.stl")
    assert result == True
    print(f"  ✓ load_data() = {result}")

    # Test get_mock_volume
    volume = analyzer.get_mock_volume(1.0)
    expected = 4.18879020478639
    assert abs(volume - expected) < 0.001
    print(f"  ✓ get_mock_volume(1.0) = {volume:.6f}")


def main():
    """Run all tests."""
    print("=" * 60)
    print("geom-core Milestone 2: Mesh Analysis Tests")
    print("=" * 60)

    try:
        test_vector3()
        test_load_stl()
        test_cube_volume()
        test_watertight()
        test_bounding_box()
        test_legacy_methods()

        print("\n" + "=" * 60)
        print("✓ All Milestone 2 tests passed!")
        print("=" * 60)
        return 0

    except AssertionError as e:
        print(f"\n✗ Test failed: {e}")
        return 1
    except Exception as e:
        print(f"\n✗ Unexpected error: {e}")
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
