/**
 * @file STLWriter.cpp
 * @brief STL file writer (binary and ASCII)
 */

#include "geom-core/cad/Types.hpp"
#include <fstream>
#include <cstring>
#include <cmath>
#include <sstream>
#include <limits>
#include <algorithm>
#include <iomanip>

namespace madfam::geom::io {

using namespace madfam::geom::cad;

namespace {

bool validMesh(const MeshData& mesh) {
    return mesh.positions.size() % 3 == 0 && mesh.indices.size() % 3 == 0 &&
        mesh.triangleCount() <= (std::numeric_limits<size_t>::max() - 84) / 50 &&
        mesh.triangleCount() <= std::numeric_limits<uint32_t>::max() &&
        std::all_of(mesh.positions.begin(), mesh.positions.end(), [](float n) { return std::isfinite(n); }) &&
        std::all_of(mesh.indices.begin(), mesh.indices.end(), [&](uint32_t i) { return i < mesh.vertexCount(); });
}

// Compute face normal from triangle vertices
void computeFaceNormal(const float* v0, const float* v1, const float* v2,
                        float& nx, float& ny, float& nz) {
    // Promote before subtraction: finite float coordinates can overflow float
    // edge products. Double covers the complete float input range.
    const double e1x = double(v1[0]) - v0[0];
    const double e1y = double(v1[1]) - v0[1];
    const double e1z = double(v1[2]) - v0[2];
    const double e2x = double(v2[0]) - v0[0];
    const double e2y = double(v2[1]) - v0[1];
    const double e2z = double(v2[2]) - v0[2];
    const double x = e1y * e2z - e1z * e2y;
    const double y = e1z * e2x - e1x * e2z;
    const double z = e1x * e2y - e1y * e2x;
    const double length = std::hypot(x, y, z);
    nx = length > 0 ? float(x / length) : 0;
    ny = length > 0 ? float(y / length) : 0;
    nz = length > 0 ? float(z / length) : 0;
}

}  // namespace

/**
 * @brief Write mesh to binary STL file
 */
Result<bool> writeSTL(const MeshData& mesh, const std::string& filepath, bool binary) {
    if (!validMesh(mesh)) return Result<bool>::error("INVALID_MESH", "Invalid triangle data");
    if (binary) {
        std::ofstream file(filepath, std::ios::binary);
        if (!file.is_open()) {
            return Result<bool>::error("IO_ERROR", "Failed to create file: " + filepath);
        }

        // Header (80 bytes)
        char header[80] = {};
        strncpy(header, "Binary STL generated by geom-core", 79);
        file.write(header, 80);

        // Triangle count
        uint32_t numTriangles = mesh.triangleCount();
        file.write(reinterpret_cast<const char*>(&numTriangles), 4);

        // Write triangles
        for (size_t i = 0; i < mesh.triangleCount(); ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[size_t(i0) * 3];
            const float* v1 = &mesh.positions[size_t(i1) * 3];
            const float* v2 = &mesh.positions[size_t(i2) * 3];

            // Compute face normal
            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            // Write normal
            file.write(reinterpret_cast<const char*>(&nx), 4);
            file.write(reinterpret_cast<const char*>(&ny), 4);
            file.write(reinterpret_cast<const char*>(&nz), 4);

            // Write vertices
            file.write(reinterpret_cast<const char*>(v0), 12);
            file.write(reinterpret_cast<const char*>(v1), 12);
            file.write(reinterpret_cast<const char*>(v2), 12);

            // Attribute byte count
            uint16_t attr = 0;
            file.write(reinterpret_cast<const char*>(&attr), 2);
        }

        file.close();
        if (!file) return Result<bool>::error("IO_ERROR", "Failed to write STL");
        return Result<bool>::ok(true);
    } else {
        // ASCII STL
        std::ofstream file(filepath);
        if (!file.is_open()) {
            return Result<bool>::error("IO_ERROR", "Failed to create file: " + filepath);
        }

        file << std::setprecision(std::numeric_limits<float>::max_digits10);
        file << "solid geom-core\n";

        for (size_t i = 0; i < mesh.triangleCount(); ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[size_t(i0) * 3];
            const float* v1 = &mesh.positions[size_t(i1) * 3];
            const float* v2 = &mesh.positions[size_t(i2) * 3];

            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            file << "  facet normal " << nx << " " << ny << " " << nz << "\n";
            file << "    outer loop\n";
            file << "      vertex " << v0[0] << " " << v0[1] << " " << v0[2] << "\n";
            file << "      vertex " << v1[0] << " " << v1[1] << " " << v1[2] << "\n";
            file << "      vertex " << v2[0] << " " << v2[1] << " " << v2[2] << "\n";
            file << "    endloop\n";
            file << "  endfacet\n";
        }

        file << "endsolid geom-core\n";

        file.close();
        if (!file) return Result<bool>::error("IO_ERROR", "Failed to write STL");
        return Result<bool>::ok(true);
    }
}

/**
 * @brief Write mesh to STL in memory buffer
 */
Result<std::vector<uint8_t>> writeSTLToMemory(const MeshData& mesh, bool binary) {
    if (!validMesh(mesh)) return Result<std::vector<uint8_t>>::error("INVALID_MESH", "Invalid triangle data");
    std::vector<uint8_t> buffer;

    if (binary) {
        // Calculate size: 80 header + 4 count + 50 per triangle
        size_t size = 84 + mesh.triangleCount() * 50;
        buffer.resize(size);

        uint8_t* ptr = buffer.data();

        // Header
        memset(ptr, 0, 80);
        strncpy(reinterpret_cast<char*>(ptr), "Binary STL generated by geom-core", 79);
        ptr += 80;

        // Triangle count
        const uint32_t triangleCount = static_cast<uint32_t>(mesh.triangleCount());
        memcpy(ptr, &triangleCount, 4);
        ptr += 4;

        // Triangles
        for (size_t i = 0; i < mesh.triangleCount(); ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[size_t(i0) * 3];
            const float* v1 = &mesh.positions[size_t(i1) * 3];
            const float* v2 = &mesh.positions[size_t(i2) * 3];

            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            memcpy(ptr, &nx, 4); ptr += 4;
            memcpy(ptr, &ny, 4); ptr += 4;
            memcpy(ptr, &nz, 4); ptr += 4;

            memcpy(ptr, v0, 12); ptr += 12;
            memcpy(ptr, v1, 12); ptr += 12;
            memcpy(ptr, v2, 12); ptr += 12;

            uint16_t attr = 0;
            memcpy(ptr, &attr, 2); ptr += 2;
        }
    } else {
        // ASCII - use string stream
        std::ostringstream ss;
        ss << std::setprecision(std::numeric_limits<float>::max_digits10);
        ss << "solid geom-core\n";

        for (size_t i = 0; i < mesh.triangleCount(); ++i) {
            uint32_t i0 = mesh.indices[i * 3 + 0];
            uint32_t i1 = mesh.indices[i * 3 + 1];
            uint32_t i2 = mesh.indices[i * 3 + 2];

            const float* v0 = &mesh.positions[size_t(i0) * 3];
            const float* v1 = &mesh.positions[size_t(i1) * 3];
            const float* v2 = &mesh.positions[size_t(i2) * 3];

            float nx, ny, nz;
            computeFaceNormal(v0, v1, v2, nx, ny, nz);

            ss << "  facet normal " << nx << " " << ny << " " << nz << "\n";
            ss << "    outer loop\n";
            ss << "      vertex " << v0[0] << " " << v0[1] << " " << v0[2] << "\n";
            ss << "      vertex " << v1[0] << " " << v1[1] << " " << v1[2] << "\n";
            ss << "      vertex " << v2[0] << " " << v2[1] << " " << v2[2] << "\n";
            ss << "    endloop\n";
            ss << "  endfacet\n";
        }

        ss << "endsolid geom-core\n";

        std::string str = ss.str();
        buffer.assign(str.begin(), str.end());
    }

    return Result<std::vector<uint8_t>>::ok(std::move(buffer));
}

}  // namespace madfam::geom::io
